'use strict';

const functions = [
  {
    name: 'get_similar_words',
    description: 'Generate similar words, synonyms, and unique compound words, based on intent and context from the user.',
    parameters: {
      type: 'object',
      properties: {
        intent: {
          type: 'string',
          description: 'Determine the user\'s intent, based on provided input, to serve as context for generating similar words and synonyms.'
        },
        inputType: {
          type: 'string',
          description: 'Type of input from the user. Use \'description\' when the user describes what they want, versus providing a simple list of words.',
          enum: ['word', 'words', 'description']
        },
        suggestions: {
          type: 'array',
          description: 'List of words generated by the AI assistant, to use as suggestions for similar words and synonyms.',
          items: { type: 'string' }
        },
        allowHyphenated: {
          type: 'boolean',
          description: 'Permit the inclusion of hyphenated words in the output',
          default: true
        },
        maxHyphenSegments: {
          type: 'integer',
          description: 'Maximum number of segments of a hyphenated word if \'allowHyphenated\' is true',
          minimum: 1,
          maximum: 2
        },
        requiredCasing: {
          type: 'string',
          description: 'Required casing for suggested words. Kebab-case (hyphenated) is the only casing allowed. This must be adhered to or the suggestions will be rejected.',
          pattern: '^[a-z]+(?:-[a-z]+)*$'
          // enum: [
          //   'lowercase',
          //   'uppercase',
          //   'kebabcase',
          //   'camelcase',
          //   'snakecase',
          //   'pascalecase',
          //   'titlecase',
          //   'propercase',
          //   'sentencecase',
          //   'preserve'
          // ]
        },
        maxWords: {
          type: 'integer',
          description: 'Upper bound for the number of similar words and synonyms in the output. There is a hard max of 100 words.',
          const: 20
        },
        minWords: {
          type: 'integer',
          description: 'Lower bound for the number of similar words and synonyms in the output. There is a hard max of 100 words.',
          const: 10
        }
      },
      required: [
        'word',
        'allowHyphenated',
        'requiredCasing',
        'maxWords',
        'minWords',
        'maxHyphenSegments',
        'inputType',
        'suggestions'
      ]
    }
  }
];

module.exports = functions;
module.exports.functions = functions;
